blueprint:
  name: IKEA Bilresa Light Control
  description: Control lights and areas with an IKEA Bilresa
  domain: automation
  input:
    button_1:
      name: Bilresa Button 1
      selector:
        entity:
          filter:
            - integration: matter
              domain: event
              device_class: button
    button_2:
      name: Bilresa Button 2
      selector:
        entity:
          filter:
            - integration: matter
              domain: event
              device_class: button
    target_lights:
      name: Lights and Areas
      default: {}
      selector:
        target:
          entity:
            domain:
              - light
    target_power:
      name: Outlets and power
      default: {}
      selector:
        target:
          entity:
            domain:
              - switch
    brightness_step:
      name: Brightness Step
      default: 20
      selector:
        number:
          min: 1
          max: 50
          step: 1

variables:
  brightness_step: !input brightness_step
  target_lights: !input target_lights
  target_power: !input target_power

trigger:
  - platform: state
    entity_id: !input button_1
    attribute: event_type
    to: multi_press_1
    id: "on"

  - platform: state
    entity_id: !input button_2
    attribute: event_type
    to: multi_press_1
    id: "off"

  - platform: state
    entity_id: !input button_1
    attribute: event_type
    to: multi_press_2
    id: "brighten"

  - platform: state
    entity_id: !input button_2
    attribute: event_type
    to: multi_press_2
    id: "dim"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - if:
              - condition: template
                value_template: "{{ target_lights != {} }}"
            then:
              - action: homeassistant.turn_on
                target: !input target_lights
          - if:
              - condition: template
                value_template: "{{ target_power != {} }}"
            then:
              - action: homeassistant.turn_on
                target: !input target_power

      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - if:
              - condition: template
                value_template: "{{ target_lights != {} }}"
            then:
              - action: homeassistant.turn_off
                target: !input target_lights
          - if:
              - condition: template
                value_template: "{{ target_power != {} }}"
            then:
              - action: homeassistant.turn_off
                target: !input target_power

      - conditions:
          - condition: trigger
            id: "brighten"
        sequence:
          - if:
              - condition: template
                value_template: "{{ target_lights != {} }}"
            then:
              - action: light.turn_on
                target: !input target_lights
                data:
                  brightness_step_pct: "{{ brightness_step }}"

      - conditions:
          - condition: trigger
            id: "dim"
        sequence:
          - if:
              - condition: template
                value_template: "{{ target_lights != {} }}"
            then:
              - action: light.turn_on
                target: !input target_lights
                data:
                  brightness_step_pct: "{{ -brightness_step }}"
